/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafxgui;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.HPos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;


//functional, needs to be cleaned up aesthetically
public class App extends Application {
    public static void main(String[] args) { launch(args); }

    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Shopping List Generator");

        Button btn1 = new Button();
        btn1.setText("Add Recipe");
        btn1.setOnAction(new EventHandler<ActionEvent>() {
            public void handle(ActionEvent event) {
                System.out.println("Adding recipe...");
                addRecipe(); }
        });

        Button btn2 = new Button();
        btn2.setText("Make Shopping List");
        btn2.setOnAction(new EventHandler<ActionEvent>() {
            public void handle(ActionEvent event) { System.out.println("Making new list...");
            try { makeShopList(); }
            catch (IOException e) { e.printStackTrace(); }
            }
        });

        Button btn3 = new Button();
        btn3.setText("Exit");
        btn3.setOnAction(new EventHandler<ActionEvent>() {
            public void handle(ActionEvent event){ primaryStage.close(); }
        });
        
        GridPane root = new GridPane();
        root.getColumnConstraints().add(new ColumnConstraints(50));
        root.getColumnConstraints().add(new ColumnConstraints(200));
        root.getColumnConstraints().add(new ColumnConstraints(200));
        root.getColumnConstraints().add(new ColumnConstraints(50));
        root.getRowConstraints().add(new RowConstraints(50));
        root.getRowConstraints().add(new RowConstraints(50));
        root.getRowConstraints().add(new RowConstraints(50));
        root.getRowConstraints().add(new RowConstraints(50));

        root.add(btn1,1,1);
        root.add(btn2,2,1);
        root.add(btn3,1,2,2,1);
        root.setHalignment(btn1, HPos.CENTER);
        root.setHalignment(btn2, HPos.CENTER);
        root.setHalignment(btn3, HPos.CENTER);
        primaryStage.setScene(new Scene(root, 500, 200));
        primaryStage.show();
    }


//functional, needs to be cleaned up aesthetically, needs instructional lables
    public void addRecipe(){
        Stage stage2 = new Stage();
        stage2.setTitle("Add Recipe");

        //take ui for recipe name
        TextField name = new TextField();
        name.setPromptText("Enter the recipe name");
        Label forName = new Label("Recipe Name:");


        //take ui for recipe servings num
        TextField serv = new TextField();
        serv.setPromptText("Enter the serving size");
        Label forServ = new Label("Serving Size:");


        //take ui for ingredients and quantities
        TextArea ing = new TextArea();
        ing.setPrefColumnCount(2);
        ing.setWrapText(false);
        ing.setPromptText("Enter the ingredients");
        Label forIng = new Label("Ingredients:\n"+"\nEnter the quantity, followed by a comma,"+
                " followed by the unit and ingredient. Example: 1, cups rice. "+
                "For oil and spices, enter no units and 0 as the quantity.");
        forIng.setWrapText(true);

        //save and exit button
        Button exit = new Button();
        exit.setText("Done");
        exit.setOnAction(new EventHandler<ActionEvent>() {
            public void handle(ActionEvent event){
                try {
                    FileWriter input = new FileWriter("recipes.txt",true);
                    input.write(name.getText()+"\n");
                    input.write(serv.getText()+"\n");
                    for(CharSequence line : ing.getParagraphs()){
                        input.write(line+"\n");
                    }
                    input.write("*\n");
                    input.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
                System.out.println("Recipe added!");
                stage2.close();}
        });

        GridPane root = new GridPane();
        root.getColumnConstraints().add(new ColumnConstraints(50));
        root.getColumnConstraints().add(new ColumnConstraints(300));
        root.getColumnConstraints().add(new ColumnConstraints(300));
        root.getColumnConstraints().add(new ColumnConstraints(50));

        root.add(forName,1,0);
        root.add(name,2,0);
        root.add(forServ,1,1);
        root.add(serv,2,1);
        root.add(forIng,1,2);
        root.add(ing,2,2);
        root.add(exit,1,3,2,1);
        root.setHalignment(exit, HPos.CENTER);

        stage2.setScene(new Scene(root,700,400));
        stage2.show();

    }


//not yet functional
    public void makeShopList() throws IOException {
        Stage stage3 = new Stage();
        stage3.setTitle("Make Shopping List");
        RecipeBook rb = RecipeBook.createBook();
        MealPlan mp = new MealPlan("mp");

        ArrayList bs = new ArrayList();
        for(String s : rb.open()){
            Button b = new Button();
            b.setText(s+"("+rb.get(s).getServings()+")");
            b.setOnAction(new EventHandler<ActionEvent>() {
                public void handle(ActionEvent event) {
                    mp.addRecipe(rb.get(s));
                //add to whatever display method is chosen
                }
            });
            bs.add(b);
        }
        //display somewhere the recipes and serving number on list

        Button exit = new Button();
        exit.setText("Print & Exit");
        exit.setOnAction(new EventHandler<ActionEvent>() {
            public void handle(ActionEvent event){
                try{
                    FileWriter output = new FileWriter("ShopList.txt");
                    output.write(mp.getName()+"\n");
                    output.write("Meals: ");
                    for(String s : mp.getMeals()){ output.write(s + ", "); }
                    output.write("\nServings: "+mp.getServings()+"\n");
                    for(String key : mp.getShopList().keySet()){
                        output.write(mp.getShopList().get(key)+key+"\n");}
                    output.close();
                }
                catch (IOException e){
                    e.printStackTrace();
                }
                stage3.close();
                System.out.println("Grocery list printed!");
            }
        });

        TilePane root = new TilePane(); //temp while i figure out how to make pretty
        root.getChildren().add(exit);
        root.getChildren().addAll(bs);
        stage3.setScene(new Scene(root,500,550));
        stage3.show();
    }
}
